using System;
using System.Collections.Generic;
using System.Text;
using TwelveEngine.Font;

namespace Elves.Scenes.Credits {
    using static CreditsItem;
    public sealed class ElfGameCreditsScene:CreditsScene {
        private static CreditsItem[] GetCreditItems() {
            var lines = new CreditsItem[] {
                Image(Program.Textures.ElvesLogo),
                LineBreak,
                Heading("Programming"),
                TextLabel("Lead","Samuel Robinson"),
                TextLabel("Support 1","N/A"),
                TextLabel("Support 2","N/A"),
                TextLabel("Support 3","N/A"),
                Link("https://github.com/samwhaleIV"),
                LineBreak,
                LineBreak,
                Heading("Music"),
                TextLabel("Producer","James Dycus"),
                TextLabel("Composer","James Dycus"),
                TextLabel("Mixer","James Dycus"),
                TextLabel("Editor","James Dycus"),
                TextLabel("Performer","James Dycus"),
                Link("https://soundcloud.com/user-768285590"),
                LineBreak,
                LineBreak,
                Heading("Art"),
                TextLabel("Sprite Work","Samuel Robinson"),
                TextLabel("Slave Driver","Boney Elf"),
                TextLabel("Drunken Slob","Boney Elf"),
                LineBreak,
                LineBreak,
                Heading("UI/UX"),
                TextLabel("Designer","Samuel Robinson"),
                TextLabel("Programmer","Samuel Robinson"),
                LineBreak,
                LineBreak,
                Heading("Quality Assurance"),
                Text("Samuel Robinson"),
                Text("James Dycus"),
                Text("Lincoln Kamp"),
                LineBreak,
                LineBreak,
                LineBreak,
                LineBreak,
                LineBreak,
                Heading("Powered by Twelve Engine."),
                Image(Program.Textures.TwelveEngineLogo),
                LineBreak,
                LineBreak,
                LineBreak,
                LineBreak,
                LineBreak,
                Heading("Made with FMOD Studio"),
                Heading("by Firelight Technologies Pty Ltd."),
                Image(Program.Textures.FMODLogo),
                Link("https://fmod.com/"),
                LineBreak,
                LineBreak,
                LineBreak,
                LineBreak,
                LineBreak,
                Heading("Made using the MonoGame framework."),
                Image(Program.Textures.MonoGameLogo),
                Link("https://www.monogame.net/"),
                LineBreak,
                LineBreak,
                LineBreak,
                LineBreak,
                LineBreak,
                Heading("Special Thanks"),
                Text("MonoGame Discord Group"),
                Text("< NAME HERE >"),
                Text("< NAME HERE >"),
                Text("< NAME HERE >"),
                Text("< NAME HERE >"),
                Text("< NAME HERE >"),
                Text("< NAME HERE >"),
                Text("< NAME HERE >"),
                Text("< NAME HERE >"),
                Text("< NAME HERE >"),
                Text("< NAME HERE >"),
                Text("< NAME HERE >"),
                Text("< NAME HERE >"),
                LineBreak,
                LineBreak,
                LineBreak,
                LineBreak,
                LineBreak,
                Heading("Most Important Person"),
                Text("You <3")
            };
            return lines;
        }
        public ElfGameCreditsScene() : base(Fonts.Retro,5,GetCreditItems()) {}
    }
}
